FROM node:20.4-slim

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

COPY . .

EXPOSE 4000

CMD ["npm", "run", "dev"]
